config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :memberships
  resources :memberships
  resources :memberships
  resources :beer_clubs
  resources :styles
  resources :beer_clubs
  resources :memberships
  resources :users
  resource :session, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to:'places#search'

  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :places, only:[:index, :show]

  root 'breweries#index'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

end

app/models/style.rb
class Style < ActiveRecord::Base
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show, :edit, :update, :destroy]

  # GET /styles
  # GET /styles.json
  def index
    @styles = Style.all
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to @style, notice: 'Style was successfully created.' }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1
  # PATCH/PUT /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    @style.destroy
    respond_to do |format|
      format.html { redirect_to styles_url, notice: 'Style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_params
      params.fetch(:style, {})
    end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_for(@style) do |f| %>
  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% @style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<h1>Editing Style</h1>

<%= render 'form' %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', styles_path %>

app/views/styles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Styles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @styles.each do |style| %>
      <tr>
        <td><%= link_to 'Show', style %></td>
        <td><%= link_to 'Edit', edit_style_path(style) %></td>
        <td><%= link_to 'Destroy', style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Style', new_style_path %>

app/views/styles/new.html.erb
<h1>New Style</h1>

<%= render 'form' %>

<%= link_to 'Back', styles_path %>

app/views/styles/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Back', styles_path %>

<%= edit_and_destroy_buttons(@style) %>